# Generated by Django 5.0.3 on 2024-03-21 16:30

import attachments.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "attachment_file",
                    models.FileField(
                        upload_to=attachments.models.attachment_upload,
                        verbose_name="attachment",
                    ),
                ),
                (
                    "attachment_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("resume", "Resume"),
                            ("misc", "Miscellaneous"),
                            ("academic", "Academic Docs"),
                            ("photo_id", "Miscellaneous"),
                            ("certificates", "Certificates"),
                        ],
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True, verbose_name="modified"),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "attachment",
                "verbose_name_plural": "attachments",
                "ordering": ["-created"],
                "permissions": (
                    ("delete_foreign_attachments", "Can delete foreign attachments"),
                ),
            },
        ),
    ]
